// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc0UE93ai9anfsFjcimDLa9DJjGdkHBP8',
    appId: '1:868639680484:web:fc2b0ad04cfc370381c9f1',
    messagingSenderId: '868639680484',
    projectId: 'mathmatric-c4bcc',
    authDomain: 'mathmatric-c4bcc.firebaseapp.com',
    storageBucket: 'mathmatric-c4bcc.firebasestorage.app',
    measurementId: 'G-0HHC6BL1C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Fhs39o6mYDkbFwa1ksSEsWcrSQShw0U',
    appId: '1:868639680484:android:91395a8a82f6e74181c9f1',
    messagingSenderId: '868639680484',
    projectId: 'mathmatric-c4bcc',
    storageBucket: 'mathmatric-c4bcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV1uNgtCHP2A5LntcZESWNClM1TNnND84',
    appId: '1:868639680484:ios:0793a8837b0ff56d81c9f1',
    messagingSenderId: '868639680484',
    projectId: 'mathmatric-c4bcc',
    storageBucket: 'mathmatric-c4bcc.firebasestorage.app',
    iosBundleId: 'com.example.mathMatric',
  );
}
